### ISSUE TITLE
赞

### ISSUE THREAD

**Issue by zxy1994** [golfxiao/sqlproxy#1]
最近也碰到了mysql切达梦的问题，也是想的b方案（中间层屏蔽差异，因为有些中间件默认的数据库就是mysql，改源码太麻烦），来githup逛一逛，没想到发现了宝贝。作者牛逼啊

**Comment by golfxiao** [comment]
哈哈，欢迎使用，如果觉得能解决一些实际问题，可以介绍给其他有需要的伙伴使用。
